In [1]:
import numpy as np

In [3]:
a = np.random.random((3,3))

In [4]:
a

array([[0.70855381, 0.01178946, 0.54880835],
       [0.84793315, 0.75019189, 0.20085962],
       [0.16420417, 0.63265418, 0.23409741]])

# 上面生成的随机数所用方法为：
# np.random.random((m,n))        (生成m行n列的随机数)
# 而且随机数的取值从为0~1

In [6]:
b=np.random.normal(size=(3,3))
b

array([[-0.03428584,  0.55890704, -1.06142838],
       [ 1.42122127, -0.05875913, -1.71341954],
       [ 1.64844374, -0.30636692, -0.81716339]])

# 上面生成的是符合标准正态分布的随机数
# 格式为： np.random.normal(size=(m,n))
# 生成m行n列的随机数

In [7]:
c = np.random.randint(0,10,size=(3,3))
c

array([[7, 5, 1],
       [3, 9, 5],
       [1, 0, 7]])

# 上面生成m到n之间的随机整数
# 格式为：np.random.randint(a,b,size=(m,n))
# 意识是生成a到b之间，m行n列的随机整数

# --------------------------------------------------------------------------------

In [9]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.sum(a1)

45

# 上面是求矩阵中所有元素相加的值
# 格式为：np.sum(array)

In [11]:
r=np.min(a1)
r

1

# 上面是求所有元素的最小值
# 格式为：np.min(array)

In [12]:
q=np.max(a1)
q

9

# 上面是求矩阵中所有元素的最大值
# 格式为：np.max(array)

In [13]:
m = np.sum(a1,axis=0)
m

array([12, 15, 18])

# 上面是对列求和
# 格式为：np.sum(array,axis=0)
## 注：axis的意思是轴、轴心的意思

In [14]:
n=np.sum(a1,axis=1)
n

array([ 6, 15, 24])

# 上面是对行求和
# 格式为：np.sum(array,axis=1)
## 注：axis的意思是轴、轴心的意思

In [15]:
np.argmin(a1)

0

# 寻找最小元素，并反回索引
# 格式为：np.argmin(array)

In [17]:
b2=np.array([[2,1,3],[4,9,5]])
b2

array([[2, 1, 3],
       [4, 9, 5]])

In [18]:
np.argmin(b2)

1

In [19]:
b3=np.array([[3,4,2],[1,7,5]])
b3

array([[3, 4, 2],
       [1, 7, 5]])

In [20]:
np.argmin(b3)

3

# 同理，求最大值的索引为：
# np.argmax(array)

In [21]:
np.argmax(b3)

4

# ---------------------------------------------------------------------------------

In [23]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.mean(a1)

5.0

# 求平均值：
# 格式为：np.mean(array)
# array.mean()

In [24]:
a1.mean()

5.0

# --------------------------------------------------------------------------------

In [26]:
np.median(a1)

5.0

# 求中位数

# --------------------------------------------------------------------------

In [27]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

# 矩阵开方（每个元素都进行开方运算）
# 格式：np.sqrt(array)

# ------------------------------------------------------------------------------------

In [30]:
a45=np.random.randint(0,10,size=(1,10))
a45

array([[6, 3, 7, 1, 6, 1, 1, 4, 3, 9]])

In [31]:
np.sort(a45)

array([[1, 1, 1, 3, 3, 4, 6, 6, 7, 9]])

# np.sort(array)
# 进行排序

# -------------------------------------------------------------------------------

In [33]:
qqq = ([[6, 3, 7, 1, 6, 1, 1, 4, 3, 9]])


In [34]:
qqq

[[6, 3, 7, 1, 6, 1, 1, 4, 3, 9]]

In [35]:
np.clip(qqq,2,7)

array([[6, 3, 7, 2, 6, 2, 2, 4, 3, 7]])

# 当向量里面的元素小于二时，会变成2，向量里面的元素大于7时会变成7