In [1]:
import numpy as np
a1=np.array([[1,2,3],[4,1,2]])

In [2]:
a2=np.array([[2,1,1],[3,5,9]])

In [5]:
c = a1+a2
c

array([[ 3,  3,  4],
       [ 7,  6, 11]])

In [8]:
d=a2-a1
d

array([[ 1, -1, -2],
       [-1,  4,  7]])

# 矩阵加法，按位加，array1 + array2
# 矩阵减法，按位减，array1 -  array2

In [9]:
s= a1*a2
s

array([[ 2,  2,  3],
       [12,  5, 18]])

# 矩阵乘法，按位乘   array1 * array2 

In [10]:
f = a1**a2
f

array([[  1,   2,   3],
       [ 64,   1, 512]], dtype=int32)

# 矩阵乘幂，按位乘幂   array1 ** array2
# 同理除法也是按位相除
# 按位取余：%
# 按位取整：//

# 上面的操作要求两个矩阵形状相同

In [14]:
l =a1+2
l

array([[3, 4, 5],
       [6, 3, 4]])

In [15]:
g= a1*10
g

array([[10, 20, 30],
       [40, 10, 20]])

# 一个矩阵与一个数相加，相当于矩阵中每个元素都加上这个数
# 一个矩阵与一个数相乘，相当于矩阵中每个元素都乘上这个数

# ---------------------------------------------------------------------

In [16]:
h= a1>3
h

array([[False, False, False],
       [ True, False, False]])

# 对矩阵中的每个元素进行判断，返回为真或假组成的矩阵
#  结果是矩阵啊啊啊

# --------------------------------------------------------------

# 下面看看真正的矩阵乘法
# np.dot(array1,array2)
# 要求上面的矩阵符合乘法规则（n x m * m x k ）

In [22]:
a2 =np.ones((3,2))
a2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
a1

array([[1, 2, 3],
       [4, 1, 2]])

In [23]:
W=np.dot(a1,a2)

In [24]:
W

array([[6., 6.],
       [7., 7.]])

# 当然矩阵乘法也可以用下面的方式
# array1.dot(array2)

In [25]:
a1.dot(a2)

array([[6., 6.],
       [7., 7.]])

### 888888888888888888888888888888888888888888888888888888888888

# 下面看一下矩阵的转置
# array.T
# np.transpose(array)

In [26]:
a1

array([[1, 2, 3],
       [4, 1, 2]])

In [27]:
a1.T

array([[1, 4],
       [2, 1],
       [3, 2]])

In [28]:
a2

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
np.transpose(a2)

array([[1., 1., 1.],
       [1., 1., 1.]])

#  计算乘积

In [1]:
import numpy as np

In [2]:
po = np.array([1,2,3,4])

In [3]:
np.prod(po)

24

po.prod()

In [9]:
po.prod(axis=0)

24

In [10]:
po.max()

4

# ----------------------------------------------------------------------------------

# 计算方差

In [11]:
po.var()

1.25

# -------------------------------------------------------------------------------

# 指定某一列进行排序，np.lexsort([])

In [16]:
np.random.randint(0,10,3)

array([3, 3, 7])