In [1]:
import numpy as np

### 定义一个矩阵

In [2]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a.ndim

2

# 查看矩阵维度：
## array.ndim

In [13]:
a.shape

(3, 3)

# 查看矩阵形状，array.shape

In [14]:
a.size

9

# 查看矩阵大小 array.size(查看有几个元素)

In [15]:
a.dtype

dtype('int32')

# 查看矩阵中每个元素的属性： array.dtype

In [16]:
c=np.array([1,2,3],dtype=np.int32)

In [18]:
c.dtype

dtype('int32')

In [19]:
d=np.array([2,3,4],dtype=np.float)

In [20]:
d.dtype

dtype('float64')

# 在定义时指定元素类型：
## a=np.array([x,x,x],dtype=np.int32)
## b=np.array([x,x,x],dtype=np.float)

In [2]:
import numpy as np

In [5]:
aa = np.array([1,2,3])     # 定义一维数组

In [6]:
aa

array([1, 2, 3])

# 上面定义了一维数组

In [8]:
bb = np.array([[1,2,3],[4,5,6]])   # 定义二维矩阵

In [9]:
bb

array([[1, 2, 3],
       [4, 5, 6]])

# 上面定义了二维矩阵

In [10]:
zero = np.zeros((2,3))

In [11]:
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

# 上面定义一个2行3列的零矩阵
## zeros((m,n))

In [12]:
one =np.ones((3,4))

In [13]:
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 上面生成一个3行4列的全1矩阵

In [18]:
empty=np.empty((3,4))

In [19]:
empty

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
print(empty)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [20]:
cc = np.arange(10)

In [21]:
cc

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 生成一个一维行向量
## np.arange(n)

In [22]:
vv= np.arange(5,12)

In [23]:
vv

array([ 5,  6,  7,  8,  9, 10, 11])

# 生成一个向量：
## np.arange(m,n)

In [24]:
xx= np.arange(1,21,3)

In [25]:
xx

array([ 1,  4,  7, 10, 13, 16, 19])

# 上面生成一个从m开始中间间隔是k的数列
## np.arange(m,n,k)

In [26]:
ss=np.arange(8).reshape(2,4)

In [27]:
ss

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

# reshape函数将一个一维向量改写成，m行n列的矩阵
##   np.range(p).reshape(m,n)
## 其中m乘n等于p

In [1]:
import numpy as np

In [2]:
ccccc=np.array([1,3,5,7,4,6,9])

In [4]:
ccccc

array([1, 3, 5, 7, 4, 6, 9])

In [5]:
np.where(ccccc>5)

(array([3, 5, 6], dtype=int64),)

In [6]:
ccccc[np.where(ccccc>5)]

array([7, 6, 9])

# np.where(ccccc>5)

In [7]:
dddd=np.array([1,2,3,4,5],dtype=float)

In [8]:
dddd

array([1., 2., 3., 4., 5.])

In [10]:
dddd.dtype

dtype('float64')

In [11]:
fffff=np.array([1,2,3.2,'str'],dtype=object)
fffff

array([1, 2, 3.2, 'str'], dtype=object)

# dddd=np.array([1,2,3,4,5],dtype=float)    指定为浮点型
# fffff=np.array([1,2,3.2,'str'],dtype=object) 里面的元素为任意类型

# 如果原来array是整型，现在想变成浮点型
# np.asarray(array1,dtype=float)
# array.astype(float32)

In [13]:
ccccc

array([1, 3, 5, 7, 4, 6, 9])

In [14]:
np.asarray(ccccc,dtype=float)

array([1., 3., 5., 7., 4., 6., 9.])

In [15]:
ccccc.astype(dtype=str)

array(['1', '3', '5', '7', '4', '6', '9'], dtype='<U11')

# ---------------------------------------------------------------------------