In [1]:
import numpy as np

In [2]:
a=np.arange(2,14)

In [3]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [4]:
a[3]

5

# 索引从零开始（从前到后），从-1开始（从后到前）
# 提取某个数据：array[m]
# 提取一串数据：array[m:n]    (从m到n-1)

In [6]:
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [5]:
a[1:5]

array([3, 4, 5, 6])

In [7]:
a[2:-1]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
a[:6]

array([2, 3, 4, 5, 6, 7])

In [9]:
a[-3:]

array([11, 12, 13])

In [11]:
b=a.reshape(3,4)

In [12]:
b

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [13]:
b[1]

array([6, 7, 8, 9])

# 上面的例子看出：
## 当对一个矩阵进行索引时：b[m]  是索引矩阵的第m行（从零开始）

In [14]:
b[-1]

array([10, 11, 12, 13])

# 从后往前数（-1开始）

# 如果想取某一行的第几个数据;
# 格式为：array[n][m] 或array[m,n]

In [15]:
b[0][2]

4

# 行的索引从零开始，列的索引也从零开始

In [22]:
b[1,1]

7

In [24]:
b[:,2]

array([ 4,  8, 12])

# 提取所有行第二列(也就是提取某一列)

# ================================================

In [26]:
for i in b:
    print(i)
    break

[2 3 4 5]


# 上面看到i 是行，按照行来迭代
# 如果想按照列迭代，array.T

In [28]:
for i in b.T:
    print(i)

[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]


# ===============================================

In [29]:
for i in b.flat:
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13


# 按照元素索引：array.flat