In [1]:
import numpy as np

In [3]:
a1=np.arange(12).reshape(3,4)

In [4]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a2,a3=np.split(a1,2,axis=1)

In [6]:
a2

array([[0, 1],
       [4, 5],
       [8, 9]])

In [7]:
a3

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

# 格式： x,y=np.split(array,m,axis=0或1)
# 把分割的结果赋值给x和y，array为被分割矩阵，m是分割成的份数，axis=0或1是按照行进列分割或者是按照行进行分割

In [10]:
x,y,z,k=np.split(a1,4,axis=1)

In [11]:
x
y
z
k

array([[ 3],
       [ 7],
       [11]])

In [12]:
x

array([[0],
       [4],
       [8]])

In [13]:
k1,k2,k3=np.array_split(a1,3,axis=1)

In [14]:
k1

array([[0, 1],
       [4, 5],
       [8, 9]])

In [15]:
k2

array([[ 2],
       [ 6],
       [10]])

In [16]:
k3

array([[ 3],
       [ 7],
       [11]])

# 不等分分割，格式为：
## k1,k2,k3=np.array_split(a1,3,axis=1)

# ------------------------------------------------------------------------------

In [17]:
V1,V2,V3=np.vsplit(a1,3)

In [18]:
V1

array([[0, 1, 2, 3]])

# V1,V2,V3=np.vsplit(a1,3)

In [23]:
H1,H2=np.hsplit(a1,2)

In [24]:
H1

array([[0, 1],
       [4, 5],
       [8, 9]])