# 打印当前numpy版本

In [2]:
import numpy as np
print(np.__version__)

1.15.4


# 构造一个全零的矩阵，并打印所占内存大小

In [9]:
z = np.zeros((5,5))
z.size      # 查看元素个数

25

In [10]:
z.itemsize # 打印每个元素所占内存大小

8

In [11]:
print('%d bytes'%(z.size*z.itemsize))

200 bytes


# 打开numpy 帮助文档

In [14]:
help(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

# 创建一个10到49的数组，并将其倒序排列
# a[::-1]  (第一个冒号代表从头开始，第二个冒号代表直到结尾，-1代表反过来)

In [16]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [18]:
b=a[::-1]        #第一个冒号代表从头开始，第二个冒号代表直到结尾，-1代表反过来
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

# 找到数组中不为零的索引
# np.nonzero(array)   (返回值是不为零的索引序号)

In [19]:
cc=np.array([1,3,0,5,7,0,9])

In [21]:
v=np.nonzero(cc)
v

(array([0, 1, 3, 4, 6], dtype=int64),)

#  构造一个3*3矩阵，并打印最大值与最小值

In [23]:
ss=np.random.random((3,3))
ss

array([[0.20972661, 0.8478149 , 0.70173632],
       [0.17812168, 0.04217108, 0.13160432],
       [0.43208943, 0.74148784, 0.82223456]])

In [27]:
print(ss.max())
print(ss.min())

0.8478149047126319
0.04217108149230886


# 构造一个5*5矩阵,最外层加上一圈零
# np.pad(array,pad_width=n,mode='constant',constant_values=0)

In [37]:
aaaa=np.ones((5,5))
bbbb = np.pad(aaaa,pad_width=1,mode = 'constant',constant_values = 0)
print(aaaa)
bbbb

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 创建一个shape为[6,7,8]的矩阵，并找第100个元素的索引值