In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
b=np.array([4,5,6])

In [5]:
c=np.vstack((a,b))

In [10]:
print(c)
c.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [11]:
d=np.hstack((a,b))
d

array([1, 2, 3, 4, 5, 6])

In [13]:
f=np.vstack((a,b,c))
f

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# 将两个矩阵垂直合并  np.vstack((array1,array2))
# 将两个矩阵水平合并  np.hstack((array1,array2))
#  np.vstack((array1,array2，array3))   将多个矩阵进行合并

# ——————————————————————————————————————————————————————————-

In [14]:
a

array([1, 2, 3])

In [15]:
b

array([4, 5, 6])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
d

array([1, 2, 3, 4, 5, 6])

In [18]:
f

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [28]:
h=np.concatenate((a,b,a))

In [29]:
h

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [40]:
q=np.array([[1,2,3],[4,5,6]])

In [39]:
w=np.array([[2,3,4],[3,4,5]])

In [41]:
aaa=np.concatenate((q,w),axis=0)

In [42]:
aaa

array([[1, 2, 3],
       [4, 5, 6],
       [2, 3, 4],
       [3, 4, 5]])

In [43]:
abc=np.concatenate((a,b),axis=0)

In [44]:
abc

array([1, 2, 3, 4, 5, 6])

In [35]:
ss=np.concatenate((a,b),axis=1)
ss

AxisError: axis 1 is out of bounds for array of dimension 1

In [45]:
aaa=np.concatenate((q,w),axis=1)

In [46]:
aaa

array([[1, 2, 3, 2, 3, 4],
       [4, 5, 6, 3, 4, 5]])

In [47]:
q

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
a

array([1, 2, 3])

In [49]:
a.T

array([1, 2, 3])

# 一维向量不能转置

In [50]:
a1=a[np.newaxis,:]
a1

array([[1, 2, 3]])

In [51]:
a1.T

array([[1],
       [2],
       [3]])

In [52]:
a1=a[:,np.newaxis]
a1

array([[1],
       [2],
       [3]])

# 增加一维就能转置了
# 格式：a1=a[np.newaxis,:] 冒号加在后面是一行三列
# 格式：a1=a[:,np.newaxis] 冒号加在前面是三行一列
